/**
 * The picture for a post: a 1080×1350 card (Instagram's 4:5) in the site's
 * style — the book logo, one headline, one line of explanation, the source.
 *
 * Drawn as SVG and rasterised with resvg, not generated by an image model:
 * image models cannot spell Armenian, and the text on the card is the point.
 * JPEG out, because it is the only format Instagram's API accepts.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';
import jpeg from 'jpeg-js';

const HERE = dirname(fileURLToPath(import.meta.url));
const BACKEND = join(HERE, '..', '..');
/**
 * One family covering Armenian AND Latin, digits and punctuation — Noto Sans
 * merged into Noto Sans Armenian (assets/fonts/build-card-fonts.py).
 *
 * Two families did not work: Noto Sans Armenian has no digits, «%» or «,»,
 * resvg's fallback left empty boxes, and switching family mid-line with
 * <tspan>s made resvg drop the WHOLE line — observed on the first cards.
 */
export const FONTS = ['MatyanCard-Regular.ttf', 'MatyanCard-Bold.ttf'].map((f) => join(BACKEND, 'assets', 'fonts', f));
export const FAMILY = 'Matyan Card';
export const LOGO = join(BACKEND, '..', 'frontend', 'public', 'logo.png');

export const CARD = { width: 1080, height: 1350 } as const;

export interface CardText {
  /** The claim, as short as it can be said. */
  headline: string;
  /** One or two sentences under it. */
  subline: string;
  /** «ՀՀ հարկային օրենսգիրք · Հոդված 258». */
  source: string;
}

export const escape = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/**
 * Greedy wrap by estimated width. resvg cannot measure text for us, so widths
 * are estimated per character — generous for Armenian, whose letters run wider
 * than Latin — and a line that would overflow breaks at the previous space.
 */
export function wrap(text: string, maxWidth: number, fontSize: number, bold: boolean, maxLines: number): string[] {
  const per = (ch: string): number =>
    ch === ' ' ? 0.28 : /[0-9.,:;%()«»՝։-]/.test(ch) ? 0.58 : bold ? 0.7 : 0.64;
  const width = (s: string): number => [...s].reduce((w, ch) => w + per(ch), 0) * fontSize;

  const lines: string[] = [];
  let line = '';
  for (const word of text.trim().split(/\s+/)) {
    const next = line ? `${line} ${word}` : word;
    if (width(next) <= maxWidth || !line) {
      line = next;
    } else {
      lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  if (lines.length <= maxLines) return lines;
  const kept = lines.slice(0, maxLines);
  kept[maxLines - 1] = `${kept[maxLines - 1]!.replace(/[\s,.;:։]+$/, '')}…`;
  return kept;
}

export function cardSvg(c: CardText): string {
  const pad = 96;
  const inner = CARD.width - pad * 2;
  const logo = readFileSync(LOGO).toString('base64');

  const headSize = 68;
  const headLines = wrap(c.headline, inner - 40, headSize, true, 5);
  const subSize = 36;
  const subLines = wrap(c.subline, inner - 40, subSize, false, 6);

  const headTop = 330;
  const headLead = Math.round(headSize * 1.22);
  const subTop = headTop + headLines.length * headLead + 56;
  const subLead = Math.round(subSize * 1.5);

  const block = (lines: string[], x: number, top: number, lead: number, attrs: string): string =>
    lines
      .map((l, i) => `<text x="${x}" y="${top + i * lead}" font-family="${FAMILY}" ${attrs}>${escape(l)}</text>`)
      .join('\n  ');

  const source = wrap(c.source, inner - 80, 30, false, 1)[0] ?? '';

  return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${CARD.width}" height="${CARD.height}" viewBox="0 0 ${CARD.width} ${CARD.height}">
  <rect width="100%" height="100%" fill="#f8f9ff"/>
  <rect x="0" y="0" width="${CARD.width}" height="14" fill="#2563eb"/>
  <image x="${pad}" y="104" width="94" height="59" xlink:href="data:image/png;base64,${logo}"/>
  <text x="${pad + 112}" y="148" font-family="${FAMILY}" font-weight="700" font-size="42" fill="#0f172a">MatyanAI</text>
  <text x="${CARD.width - pad}" y="146" text-anchor="end" font-family="${FAMILY}" font-weight="700" font-size="32" fill="#2563eb">matyanai.am</text>
  <rect x="${pad}" y="${headTop - headSize + 6}" width="8" height="${headLines.length * headLead - 14}" rx="4" fill="#2563eb"/>
  ${block(headLines, pad + 32, headTop, headLead, `font-weight="700" font-size="${headSize}" fill="#0f172a"`)}
  ${block(subLines, pad + 32, subTop, subLead, `font-size="${subSize}" fill="#334155"`)}
  <rect x="${pad}" y="${CARD.height - 250}" width="${inner}" height="92" rx="46" fill="#eff6ff" stroke="#bfdbfe" stroke-width="2"/>
  <circle cx="${pad + 46}" cy="${CARD.height - 204}" r="7" fill="#2563eb"/>
  ${block([source], pad + 72, CARD.height - 194, 0, 'font-size="30" fill="#1d4ed8"')}
  ${block(['Տեղեկատվական նյութ, ոչ իրավաբանական խորհրդատվություն'], pad, CARD.height - 92, 0, 'font-size="26" fill="#64748b"')}
</svg>`;
}

/** The card as JPEG bytes. */
export function renderCard(c: CardText): Buffer {
  const png = new Resvg(cardSvg(c), {
    font: { fontFiles: FONTS, loadSystemFonts: false, defaultFontFamily: FAMILY },
  }).render();
  const encoded = jpeg.encode({ data: png.pixels, width: png.width, height: png.height }, 90);
  return Buffer.from(encoded.data);
}
